import Head from 'next/head'
import Link from 'next/link';
import { useRouter } from 'next/router';
import IdiomSelector from '../components/idiomSelector'


export default function Home( props ) {

  const { home } = props;
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Idiom Selector</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <p><Link href='/contact' locale={router.locale}>Contact</Link></p>
        <IdiomSelector/>
        <h1>{home.welcome}</h1>
      </main>
    </>
  )
}


export async function getStaticProps({ locale }) {
  // const response = await fetch('URL');  //Esto si fuese con un apiRest
  // const result = await response.json();


  const response = await import(`../idioms/${locale}.json`)

  return {
      props: {
          home: response.default.home
      }
  }
}
